% Tag_list
% TAGGED
% EVERTAGGED
% NUM_EVERTAGGED
% EVERTAGGED_IX
% IXLOC;
function [LIST_TAGGED, TAGGED, EVERTAGGED, NUM_EVERTAGGED, EVERTAGGED_IX] =...
    TAG_BAND(NX, IXLOC, T, LIST_TAGGED, TAGGED, EVERTAGGED, NUM_EVERTAGGED, EVERTAGGED_IX, BANDTHICKNESS, ...
    FuelMap, M1, M10, M100, MLH, MLW, U_wind, WAF)

IXTAGSTART = max(3,    IXLOC - BANDTHICKNESS);
IXTAGSTOP  = min(NX-2, IXLOC + BANDTHICKNESS);

for IX_BAND = IXTAGSTART:IXTAGSTOP
   if (~TAGGED(IX_BAND) && (~ EVERTAGGED(IX_BAND)) )
      TAGGED(IX_BAND) = true;
      EVERTAGGED(IX_BAND) = true;
      LIST_TAGGED = APPEND(LIST_TAGGED, IX_BAND, false, T, FuelMap, M1, M10, M100, MLH, MLW, 0, U_wind, WAF);
      NUM_EVERTAGGED = NUM_EVERTAGGED + 1;
      EVERTAGGED_IX(NUM_EVERTAGGED) = IX_BAND;
   end
end

end